{
 "title": "JWT Pizza",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "barchart",
   "description": "Number of active users",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Total Users"
    }
   ]
  },
  {
   "title": "Total Bitcoins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(revenue_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "description": "Average amount of bitcoins generated in the last hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1h])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Auth counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_success_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Auth Sucesses"
    },
    {
     "expr": "rate(auth_failure_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Auth Failures"
    }
   ]
  },
  {
   "title": "HTTPS Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(get_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(put_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(post_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(delete_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Pizza Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizza_errors_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Errors"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "rate(pizza_latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 27 },
   "targets": [
    {
     "expr": "rate(latency_milliseconds_total{source=\"jwt-pizza-service\"}[5s])",
     "legendFormat": "Latency"
    },
    {
     "expr": "avg_over_time(latency_milliseconds_total{source=\"jwt-pizza-service-dev\"}[10m])",
     "legendFormat": "Average Latency"
    }
   ]
  }
 ]
}